---
functional:
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность удалять товары из корзины и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - При фильтрации товаров, они должны выводиться постранично
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  
non-functional:
  - Сайт должен иметь адаптивную верстку
  - Магазин должен являться SPA-приложением, которое не перезагружает страницу
  - На странице товара и в каталоге должны выводиться название, рейтинг, цена со скидкой и без нее
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  
implicit:
  - Логотип должен вести на главную страницу
  - Пользователь должен иметь возможность очищать корзину
  - На сайте должна быть возможность оплатить заказ
