---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Удаление товара из корзины сопровождается запросом подтверждения удаления
  - Очистка корзины сопровождается запросом на подтверждение очистки
  - Выбранный язык сохраняется между сессиями
  - Логотип "Hexlet Store" в шапке сайта перенаправляет на главную страницу
  - На странице с товарами выведен список товаров, или сообщение о причине их отсутствия ("товары отсутствуют"/"произошла ошибка загрузки списка товаров")
  - Локализация формата валют
